### ISSUE TITLE
API Metrics

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Project/api#13]
Track things like 
- Users usage (by endpoint, overall, etc)
- User approximate geolocation/region
- Anything else is a bonus

**ALL METRICS SHOULD ONLY BE ACCESSED BY ADMIN OR THE USER THAT THE DATA CORRESPONDS TO**

**Comment by j-dogcoder** [comment]
Not stale!!

**Comment by satyap54** [comment]
Hi, I would like to take up this issue. What are the contribution guidelines?

**Comment by j-dogcoder** [comment]
Hey @satyap54! We don't have contribution guidelines here, as we have yet to set them up, but you are welcome to take this issue!

**Comment by j-dogcoder** [comment]
Would you like me to assign it to you?

**Comment by satyap54** [comment]
Yes, I would like to take up this issue.

**Comment by satyap54** [comment]
There are two APIs that I found that could be used:

- https://www.ipinfodb.com/api  (Rate limit: 2 queries/sec)
- https://ipinfo.io/developers#authentication (Rate limit: 50,000 queries/month)

I need some input on which one to integrate.

**Comment by j-dogcoder** [comment]
Lets use ipinfo.io please @satyap54!

**Comment by satyap54** [comment]
Are we going to store the whole history? Won't that be a lot to display? Or should I have a pagination end-pt in place?

**Comment by j-dogcoder** [comment]
Hey @satyap54, lets store the whole thing, but paginate what we display.

**Comment by satyap54** [comment]
So, will it be a backend pagination or frontend?

**Comment by j-dogcoder** [comment]
backend

**Comment by satyap54** [comment]
"remote: Permission to Heptagram-Project/api.git denied to satyap54."
Can I get permission to contribute?

**Comment by satyap54** [comment]
I've the changes ready, please add me as a contributor.

**Comment by j-dogcoder** [comment]
@satyap54 You have to fork the repo, push to your fork, then open a PR

**Comment by j-dogcoder** [comment]
I recommend you check out the [firstcontributions guide](https://github.com/firstcontributions/first-contributions/blob/main/README.md) if you need help with how to do this, but you can also check out the [resources provided by freeCodeCamp](https://github.com/freeCodeCamp/how-to-contribute-to-open-source).

**Comment by satyap54** [comment]
Won't it be easier if you add me as a contributer ? I can push to a feature branch and you can review the PR. You can later remove my role? It would decrease the overhead for me as of now.

**Comment by j-dogcoder** [comment]
We do not give anyone direct push access. This lets us keep our codebase as clean as possible.
