### ISSUE TITLE
Switch fully to docker

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Project/api#157]
Switch the API to completely run using docker.

**Comment by 90r1ll4** [comment]
can you sign this to me?

**Comment by j-dogcoder** [comment]
Sure!

**Comment by j-dogcoder** [comment]
You can reference #47 and #48, because both of those have docker things that should be added. I would also be happy to assign you to either or both of those issues if you want to tackle them as well.

**Comment by 90r1ll4** [comment]
thanks, i am new in opensource can you please give me more detail on this API using docker issue?

**Comment by j-dogcoder** [comment]
Currently the API runs using PM2 and the `NPM run start ` command. The goal is to dockerize the process. @90r1ll4 do you have experience with docker?

**Comment by 90r1ll4** [comment]
Yes, i have experience with docker, not much with open source

**Comment by j-dogcoder** [comment]
Ok!
