### ISSUE TITLE
Setup Github Actions

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Project/api#26]
Setup some cool Github actions for our project. (_see list below_).

- [ ] [First Interaction](https://github.com/marketplace/actions/first-interaction)
- [ ] [Close Stale Issues](https://github.com/marketplace/actions/close-stale-issues)
- [ ] [Automatic Releases](https://github.com/marketplace/actions/automatic-releases)
- [ ] More TBD

**Comment by KendallDoesCoding** [comment]
@j-dogcoder I think you will have the make a token in the repo/env for this to work for others to setup, please make a token called secrets.GITHUB_TOKEN... Feel free to reach out if you need any help.

**Comment by j-dogcoder** [comment]
I have done that already!

**Comment by KendallDoesCoding** [comment]
ok cool!

**Comment by ank1traj** [comment]
Provide me with the GitHub Secret Token.

**Comment by j-dogcoder** [comment]
I don't provide that @ank1traj. It is stored in Github using `secrets.GITHUB_TOKEN`

**Comment by ank1traj** [comment]
I was not asking about the Token. Just need the name of the token. And, I think you stored it with `secrets.GITHUB_TOKEN`

**Comment by j-dogcoder** [comment]
> I was not asking about the Token. Just need the name of the token. And, I think you stored it with `secrets.GITHUB_TOKEN`

That is correct

**Comment by ank1traj** [comment]
Added the actions and created the [PR](https://github.com/Heptagram-Project/api/pull/52). Please review it and give the feedback.

**Comment by ank1traj** [comment]
@j-dogcoder We can add more GitHub actions like PR badge.
